=== kerly28/LLENGUATGE-DE-MARQUES/XSD/enunciat5/kerly.guanoquiza.7e8.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="receptes">
        <xs:complexType>
            <xs:sequence>
                <xs:element  name="recepta" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="autor">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string"/>
                                        <xs:element name="dni" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingredient">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="quantitat">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="valor" type="xs:integer"/>
                                                                <xs:element name="mesura" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="nom" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="passos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pas" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="dificultat" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kerly28/LLENGUATGE-DE-MARQUES/XSD/enunciat5/enunciat5.xml
<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="kerly.guanoquiza.7e8.xsd">
    <recepta dificultat="5">
        <autor>
            <nom>Marc Iba√±ez</nom>
            <dni>45784548F</dni>
        </autor>
        <nom>Patates amb llet</nom>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>grams</mesura>
                </quantitat>
                <nom>all</nom>
            </ingredient>
        </ingredients>
        <passos>
            <pas>Fregir patates</pas>
        </passos>
    </recepta>
</receptes>
